00: (                       switch_on instrument0 satellite0) [1]
01: (          turn_to satellite0 groundstation2 phenomenon8) [1]
02: (        calibrate satellite0 instrument0 groundstation2) [1]
03: (              turn_to satellite0 planet9 groundstation2) [1]
04: (take_image satellite0 planet9 instrument0 spectrograph1) [1]
05: (                 turn_to satellite0 phenomenon6 planet9) [1]
06: (   take_image satellite0 phenomenon6 instrument0 image2) [1]
07: (                   turn_to satellite0 star3 phenomenon6) [1]
08: (   take_image satellite0 star3 instrument0 thermograph0) [1]
09: (                         turn_to satellite0 star7 star3) [1]
10: (   take_image satellite0 star7 instrument0 thermograph0) [1]
11: (                   turn_to satellite0 phenomenon8 star7) [1]
12: (   take_image satellite0 phenomenon8 instrument0 image2) [1]
13: (             turn_to satellite0 phenomenon5 phenomenon8) [1]
14: (   take_image satellite0 phenomenon5 instrument0 image2) [1]

