    0: (grasp right shot1)[1]
    1: (fill-shot shot1 ingredient4 right left dispenser4)[1]
    2: (pour-shot-to-clean-shaker shot1 ingredient4 shaker1 right l0 l1)[1]
    3: (clean-shot shot1 ingredient4 right left)[1]
    4: (fill-shot shot1 ingredient1 right left dispenser1)[1]
    5: (pour-shot-to-used-shaker shot1 ingredient1 shaker1 right l1 l2)[1]
    6: (clean-shot shot1 ingredient1 right left)[1]
    7: (leave right shot1)[1]
    8: (grasp left shaker1)[1]
    9: (shake cocktail4 ingredient4 ingredient1 shaker1 left right)[1]
   10: (pour-shaker-to-shot cocktail4 shot1 left shaker1 l2 l1)[1]
   11: (empty-shaker left shaker1 cocktail4 l1 l0)[1]
   12: (clean-shaker left right shaker1)[1]
   13: (leave left shaker1)[1]

