0 :      (switch_on instrument8 satellite2)[1]
1 :      (turn_to satellite2 groundstation0 phenomenon5)[1]
2 :      (calibrate satellite2 instrument8 groundstation0)[1]
3 :      (turn_to satellite2 star3 groundstation0)[1]
4 :      (take_image satellite2 star3 instrument8 thermograph0)[1]
5 :      (turn_to satellite2 phenomenon5 star3)[1]
6 :      (take_image satellite2 phenomenon5 instrument8 image2)[1]
7 :     (turn_to satellite2 phenomenon6 phenomenon5)[1]
8 :     (take_image satellite2 phenomenon6 instrument8 image2)[1]
9 :     (turn_to satellite2 star7 phenomenon6)[1]
10 :     (take_image satellite2 star7 instrument8 thermograph0)[1]
11 :     (turn_to satellite2 phenomenon8 star7)[1]
12 :     (take_image satellite2 phenomenon8 instrument8 image2)[1]
13 :     (turn_to satellite2 planet9 phenomenon8)[1]
14 :     (take_image satellite2 planet9 instrument8 spectrograph1)[1]
15 :     (turn_to satellite0 phenomenon5 phenomenon8)[1]
