0 :      (switch_on instrument1 satellite0)[1]
1 :      (turn_to satellite0 groundstation2 planet4)[1]
2 :      (calibrate satellite0 instrument1 groundstation2)[1]
3 :      (turn_to satellite0 planet3 groundstation2)[1]
4 :      (take_image satellite0 planet3 instrument1 infrared0)[1]
5 :      (turn_to satellite0 planet4 planet3)[1]
6 :      (take_image satellite0 planet4 instrument1 infrared0)[1]
7 :     (turn_to satellite0 phenomenon5 planet4)[1]
8 :     (take_image satellite0 phenomenon5 instrument1 image2)[1]
9 :     (turn_to satellite0 phenomenon6 phenomenon5)[1]
10 :     (take_image satellite0 phenomenon6 instrument1 infrared0)[1]
11 :     (turn_to satellite0 star7 phenomenon6)[1]
12 :     (take_image satellite0 star7 instrument1 infrared0)[1]
