0 :      (visit shrimp)[1]
1 :      (feast aesthetics shrimp cherry quebec bosnia)[1]
2 :      (visit cherry)[1]
3 :      (feast aesthetics cherry arugula oregon kentucky)[1]
4 :      (visit arugula)[1]
5 :      (feast aesthetics arugula scallop oregon kentucky)[1]
6 :      (visit scallop)[1]
7 :      (feast aesthetics scallop grapefruit bosnia oregon)[1]
8 :      (unvisit scallop)[1]
9 :      (unvisit arugula)[1]
10 :     (unvisit cherry)[1]
11 :     (unvisit shrimp)[1]
12 :     (overcome sciatica aesthetics grapefruit mars vulcan)[1]
