0 :      (overcome abrasion rest pork uranus venus)[1]
1 :      (visit pork)[1]
2 :      (feast rest pork lamb alsace quebec)[1]
3 :      (visit lamb)[1]
4 :      (feast rest lamb flounder surrey pennsylvania)[1]
5 :      (visit flounder)[1]
6 :      (feast rest flounder rice pennsylvania alsace)[1]
7 :      (unvisit flounder)[1]
8 :      (unvisit lamb)[1]
9 :     (unvisit pork)[1]
10 :     (succumb abrasion rest rice uranus venus)[1]
