0 :      (pick ball2 rooma left)[1]
1 :      (pick ball1 rooma right)[1]
2 :      (move rooma roomb)[1]
3 :      (drop ball2 roomb left)[1]
4 :      (drop ball1 roomb right)[1]
5 :      (move roomb rooma)[1]
6 :      (pick ball4 rooma left)[1]
7 :      (pick ball3 rooma right)[1]
8 :      (move rooma roomb)[1]
9 :     (drop ball4 roomb left)[1]
10 :     (drop ball3 roomb right)[1]
11 :     (move roomb rooma)[1]
12 :     (pick ball6 rooma left)[1]
13 :     (pick ball5 rooma right)[1]
14 :     (move rooma roomb)[1]
15 :     (drop ball6 roomb left)[1]
16 :     (drop ball5 roomb right)[1]
