0 :  (overcome abrasion rest pork uranus venus  )  
1 :  (feast rest pork lamb alsace quebec  )  
2 :  (visit pork  )  
3 :  (feast rest lamb flounder surrey pennsylvania  )  
4 :  (visit lamb  )  
5 :  (feast rest flounder rice pennsylvania alsace  )  
6 :  (unvisit lamb  )  
7 :  (unvisit pork  )  
8 :  (succumb abrasion rest rice uranus venus  )  
