0 :  (overcome abrasion rest pork uranus venus  )  
1 :  (feast rest pork lamb alsace quebec  )  
2 :  (feast rest lamb flounder surrey pennsylvania  )  
3 :  (feast rest flounder rice pennsylvania alsace  )  
4 :  (succumb abrasion rest rice uranus venus  )  
