0 :      (unstack b c)[1]
1 :      (put-down b)[1]
2 :      (unstack c a)[1]
3 :      (put-down c)[1]
4 :      (unstack a d)[1]
5 :      (stack a b)[1]
6 :     (pick-up c)[1]
7 :     (stack c a)[1]
8 :     (pick-up d)[1]
9 :     (stack d c)[1]
