0 :  (unstack C G  )  
1 :  (put-down C  )  
2 :  (unstack G E  )  
3 :  (put-down G  )  
4 :  (unstack E I  )  
5 :  (put-down E  )  
6 :  (unstack I J  )  
7 :  (put-down I  )  
8 :  (unstack J A  )  
9 :  (put-down J  )  
10 :  (pick-up G  )  
11 :  (stack G J  )  
12 :  (unstack F D  )  
13 :  (put-down F  )  
14 :  (unstack D H  )  
15 :  (put-down D  )  
16 :  (pick-up H  )  
17 :  (stack H G  )  
18 :  (pick-up E  )  
19 :  (stack E H  )  
20 :  (unstack A B  )  
21 :  (stack A E  )  
22 :  (pick-up I  )  
23 :  (stack I A  )  
24 :  (pick-up F  )  
25 :  (stack F I  )  
26 :  (pick-up D  )  
27 :  (stack D F  )  
28 :  (pick-up B  )  
29 :  (stack B D  )  
30 :  (pick-up C  )  
31 :  (stack C B  )  
