0 :  (unstack E G  )  
1 :  (put-down E  )  
2 :  (unstack G B  )  
3 :  (put-down G  )  
4 :  (unstack B A  )  
5 :  (put-down B  )  
6 :  (unstack A F  )  
7 :  (put-down A  )  
8 :  (unstack F C  )  
9 :  (stack F E  )  
10 :  (unstack C D  )  
11 :  (stack C F  )  
12 :  (pick-up B  )  
13 :  (stack B C  )  
14 :  (pick-up D  )  
15 :  (stack D B  )  
16 :  (pick-up G  )  
17 :  (stack G D  )  
18 :  (pick-up A  )  
19 :  (stack A G  )  
