0 :  (unstack C D  )  
1 :  (put-down C  )  
2 :  (unstack D B  )  
3 :  (put-down D  )  
4 :  (pick-up C  )  
5 :  (stack C D  )  
6 :  (unstack A G  )  
7 :  (put-down A  )  
8 :  (pick-up G  )  
9 :  (stack G C  )  
10 :  (unstack B E  )  
11 :  (put-down B  )  
12 :  (unstack E F  )  
13 :  (put-down E  )  
14 :  (pick-up F  )  
15 :  (stack F G  )  
16 :  (pick-up B  )  
17 :  (stack B F  )  
18 :  (pick-up E  )  
19 :  (stack E B  )  
20 :  (pick-up A  )  
21 :  (stack A E  )  
