0 :  (unstack B C  )  
1 :  (put-down B  )  
2 :  (unstack C A  )  
3 :  (put-down C  )  
4 :  (unstack A D  )  
5 :  (stack A B  )  
6 :  (unstack A B  )  
7 :  (put-down A  )  
8 :  (pick-up C  )  
9 :  (stack C A  )  
10 :  (unstack C A  )  
11 :  (put-down C  )  
12 :  (pick-up D  )  
13 :  (stack D C  )  
