0 :  (unstack F L  )  
1 :  (put-down F  )  
2 :  (unstack L M  )  
3 :  (put-down L  )  
4 :  (unstack M J  )  
5 :  (put-down M  )  
6 :  (unstack J P  )  
7 :  (put-down J  )  
8 :  (unstack P N  )  
9 :  (put-down P  )  
10 :  (unstack N I  )  
11 :  (put-down N  )  
12 :  (unstack I B  )  
13 :  (put-down I  )  
14 :  (unstack B D  )  
15 :  (put-down B  )  
16 :  (unstack D C  )  
17 :  (put-down D  )  
18 :  (unstack O G  )  
19 :  (put-down O  )  
20 :  (unstack C K  )  
21 :  (stack C O  )  
22 :  (pick-up M  )  
23 :  (stack M C  )  
24 :  (unstack H E  )  
25 :  (put-down H  )  
26 :  (pick-up E  )  
27 :  (stack E M  )  
28 :  (pick-up N  )  
29 :  (stack N E  )  
30 :  (unstack K A  )  
31 :  (put-down K  )  
32 :  (pick-up A  )  
33 :  (stack A N  )  
34 :  (pick-up H  )  
35 :  (stack H A  )  
36 :  (pick-up J  )  
37 :  (stack J H  )  
38 :  (pick-up L  )  
39 :  (stack L J  )  
40 :  (pick-up I  )  
41 :  (stack I L  )  
42 :  (pick-up K  )  
43 :  (stack K I  )  
44 :  (pick-up G  )  
45 :  (stack G K  )  
46 :  (pick-up F  )  
47 :  (stack F G  )  
48 :  (pick-up P  )  
49 :  (stack P F  )  
50 :  (pick-up B  )  
51 :  (stack B P  )  
52 :  (pick-up D  )  
53 :  (stack D B  )  
