0 :  (unstack B F  )  
1 :  (put-down B  )  
2 :  (unstack F D  )  
3 :  (put-down F  )  
4 :  (unstack D C  )  
5 :  (put-down D  )  
6 :  (unstack C J  )  
7 :  (put-down C  )  
8 :  (unstack J A  )  
9 :  (put-down J  )  
10 :  (unstack A E  )  
11 :  (put-down A  )  
12 :  (unstack E H  )  
13 :  (put-down E  )  
14 :  (unstack H L  )  
15 :  (put-down H  )  
16 :  (unstack L K  )  
17 :  (put-down L  )  
18 :  (pick-up B  )  
19 :  (stack B K  )  
20 :  (pick-up J  )  
21 :  (stack J B  )  
22 :  (pick-up L  )  
23 :  (stack L J  )  
24 :  (pick-up E  )  
25 :  (stack E L  )  
26 :  (pick-up H  )  
27 :  (stack H E  )  
28 :  (pick-up M  )  
29 :  (stack M H  )  
30 :  (pick-up A  )  
31 :  (stack A M  )  
32 :  (pick-up F  )  
33 :  (stack F A  )  
34 :  (pick-up D  )  
35 :  (stack D F  )  
36 :  (pick-up C  )  
37 :  (stack C D  )  
38 :  (unstack I G  )  
39 :  (stack I C  )  
40 :  (pick-up G  )  
41 :  (stack G I  )  
