0 :  (unstack C G  )  
1 :  (put-down C  )  
2 :  (unstack G H  )  
3 :  (put-down G  )  
4 :  (unstack H I  )  
5 :  (put-down H  )  
6 :  (unstack K D  )  
7 :  (put-down K  )  
8 :  (unstack I F  )  
9 :  (stack I D  )  
10 :  (unstack F B  )  
11 :  (put-down F  )  
12 :  (unstack B A  )  
13 :  (stack B I  )  
14 :  (pick-up G  )  
15 :  (stack G B  )  
16 :  (unstack A L  )  
17 :  (put-down A  )  
18 :  (unstack L E  )  
19 :  (stack L G  )  
20 :  (pick-up F  )  
21 :  (stack F L  )  
22 :  (pick-up A  )  
23 :  (stack A F  )  
24 :  (pick-up H  )  
25 :  (stack H A  )  
26 :  (pick-up K  )  
27 :  (stack K H  )  
28 :  (unstack E J  )  
29 :  (stack E K  )  
30 :  (pick-up C  )  
31 :  (stack C E  )  
32 :  (pick-up J  )  
33 :  (stack J C  )  
