0 :  (unstack C B  )  
1 :  (stack C D  )  
2 :  (unstack C D  )  
3 :  (put-down C  )  
4 :  (pick-up B  )  
5 :  (stack B C  )  
6 :  (unstack B C  )  
7 :  (put-down B  )  
8 :  (pick-up A  )  
9 :  (stack A B  )  
