0 :  (unstack C E  )  
1 :  (put-down C  )  
2 :  (pick-up D  )  
3 :  (stack D C  )  
4 :  (unstack E B  )  
5 :  (put-down E  )  
6 :  (unstack D C  )  
7 :  (put-down D  )  
8 :  (unstack B A  )  
9 :  (stack B D  )  
10 :  (unstack B D  )  
11 :  (put-down B  )  
12 :  (pick-up E  )  
13 :  (stack E B  )  
14 :  (unstack E B  )  
15 :  (put-down E  )  
16 :  (pick-up A  )  
17 :  (stack A E  )  
