0 :  (unstack D E  )  
1 :  (put-down D  )  
2 :  (unstack E C  )  
3 :  (put-down E  )  
4 :  (unstack C A  )  
5 :  (put-down C  )  
6 :  (unstack A B  )  
7 :  (put-down A  )  
8 :  (pick-up E  )  
9 :  (stack E A  )  
10 :  (pick-up B  )  
11 :  (stack B E  )  
12 :  (pick-up C  )  
13 :  (stack C B  )  
14 :  (pick-up D  )  
15 :  (stack D C  )  
