0 :  (unstack C E  )  
1 :  (put-down C  )  
2 :  (unstack E J  )  
3 :  (put-down E  )  
4 :  (unstack J B  )  
5 :  (put-down J  )  
6 :  (unstack B G  )  
7 :  (put-down B  )  
8 :  (unstack G H  )  
9 :  (put-down G  )  
10 :  (unstack H A  )  
11 :  (put-down H  )  
12 :  (unstack A D  )  
13 :  (put-down A  )  
14 :  (unstack D I  )  
15 :  (put-down D  )  
16 :  (pick-up G  )  
17 :  (stack G I  )  
18 :  (pick-up A  )  
19 :  (stack A G  )  
20 :  (pick-up B  )  
21 :  (stack B A  )  
22 :  (pick-up H  )  
23 :  (stack H B  )  
24 :  (pick-up E  )  
25 :  (stack E H  )  
26 :  (pick-up J  )  
27 :  (stack J E  )  
28 :  (pick-up F  )  
29 :  (stack F J  )  
30 :  (pick-up C  )  
31 :  (stack C F  )  
32 :  (pick-up D  )  
33 :  (stack D C  )  
