0 :  (unstack L F  )  
1 :  (put-down L  )  
2 :  (unstack G D  )  
3 :  (put-down G  )  
4 :  (unstack D C  )  
5 :  (put-down D  )  
6 :  (unstack F E  )  
7 :  (stack F D  )  
8 :  (unstack E K  )  
9 :  (put-down E  )  
10 :  (pick-up K  )  
11 :  (stack K F  )  
12 :  (unstack Q A  )  
13 :  (put-down Q  )  
14 :  (unstack A J  )  
15 :  (put-down A  )  
16 :  (unstack J I  )  
17 :  (put-down J  )  
18 :  (unstack I B  )  
19 :  (stack I K  )  
20 :  (unstack B M  )  
21 :  (stack B I  )  
22 :  (pick-up G  )  
23 :  (stack G B  )  
24 :  (pick-up A  )  
25 :  (stack A G  )  
26 :  (pick-up P  )  
27 :  (stack P A  )  
28 :  (pick-up M  )  
29 :  (stack M P  )  
30 :  (pick-up E  )  
31 :  (stack E M  )  
32 :  (unstack C O  )  
33 :  (stack C E  )  
34 :  (unstack H N  )  
35 :  (stack H C  )  
36 :  (pick-up J  )  
37 :  (stack J H  )  
38 :  (pick-up O  )  
39 :  (stack O J  )  
40 :  (pick-up L  )  
41 :  (stack L O  )  
42 :  (pick-up N  )  
43 :  (stack N L  )  
44 :  (pick-up Q  )  
45 :  (stack Q N  )  
