0 :  (unstack B C  )  
1 :  (put-down B  )  
2 :  (unstack C G  )  
3 :  (put-down C  )  
4 :  (unstack G E  )  
5 :  (put-down G  )  
6 :  (pick-up C  )  
7 :  (stack C G  )  
8 :  (unstack A D  )  
9 :  (stack A C  )  
10 :  (pick-up D  )  
11 :  (stack D A  )  
12 :  (unstack E F  )  
13 :  (put-down E  )  
14 :  (pick-up F  )  
15 :  (stack F D  )  
16 :  (pick-up B  )  
17 :  (stack B F  )  
18 :  (pick-up E  )  
19 :  (stack E B  )  
