0 :  (unstack J I  )  
1 :  (put-down J  )  
2 :  (unstack I H  )  
3 :  (put-down I  )  
4 :  (unstack H F  )  
5 :  (put-down H  )  
6 :  (unstack F D  )  
7 :  (put-down F  )  
8 :  (unstack D E  )  
9 :  (put-down D  )  
10 :  (pick-up J  )  
11 :  (stack J D  )  
12 :  (pick-up F  )  
13 :  (stack F J  )  
14 :  (unstack E G  )  
15 :  (put-down E  )  
16 :  (unstack G B  )  
17 :  (put-down G  )  
18 :  (unstack B A  )  
19 :  (put-down B  )  
20 :  (pick-up A  )  
21 :  (stack A F  )  
22 :  (pick-up C  )  
23 :  (stack C A  )  
24 :  (pick-up H  )  
25 :  (stack H C  )  
26 :  (pick-up G  )  
27 :  (stack G H  )  
28 :  (pick-up I  )  
29 :  (stack I G  )  
30 :  (pick-up E  )  
31 :  (stack E I  )  
32 :  (pick-up B  )  
33 :  (stack B E  )  
