0 :  (unstack F G  )  
1 :  (put-down F  )  
2 :  (unstack G E  )  
3 :  (put-down G  )  
4 :  (unstack E A  )  
5 :  (put-down E  )  
6 :  (unstack A I  )  
7 :  (put-down A  )  
8 :  (unstack I D  )  
9 :  (put-down I  )  
10 :  (unstack D H  )  
11 :  (put-down D  )  
12 :  (unstack H B  )  
13 :  (put-down H  )  
14 :  (pick-up E  )  
15 :  (stack E H  )  
16 :  (pick-up F  )  
17 :  (stack F E  )  
18 :  (pick-up I  )  
19 :  (stack I F  )  
20 :  (pick-up A  )  
21 :  (stack A I  )  
22 :  (pick-up C  )  
23 :  (stack C A  )  
24 :  (pick-up B  )  
25 :  (stack B C  )  
26 :  (pick-up D  )  
27 :  (stack D B  )  
28 :  (pick-up G  )  
29 :  (stack G D  )  
