0 :  (unstack H A  )  
1 :  (put-down H  )  
2 :  (unstack A D  )  
3 :  (put-down A  )  
4 :  (unstack D E  )  
5 :  (put-down D  )  
6 :  (unstack E C  )  
7 :  (put-down E  )  
8 :  (unstack C I  )  
9 :  (stack C A  )  
10 :  (unstack I B  )  
11 :  (put-down I  )  
12 :  (unstack B G  )  
13 :  (stack B C  )  
14 :  (pick-up E  )  
15 :  (stack E B  )  
16 :  (pick-up I  )  
17 :  (stack I E  )  
18 :  (pick-up D  )  
19 :  (stack D I  )  
20 :  (pick-up H  )  
21 :  (stack H D  )  
22 :  (pick-up G  )  
23 :  (stack G H  )  
24 :  (pick-up F  )  
25 :  (stack F G  )  
