/* Generated By:JavaCC: Do not edit this line. LexerConstants.java */
package pddl4j.parser.lexer;

public interface LexerConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int LEFT_BRACKET = 13;
  int RIGHT_BRACKET = 14;
  int DEFINE = 15;
  int DOMAIN = 16;
  int REQUIREMENTS = 17;
  int TYPES = 18;
  int EITHER = 19;
  int CONSTANTS = 20;
  int PREDICATES = 21;
  int FUNCTIONS = 22;
  int ACTION = 23;
  int PARAMETERS = 24;
  int PRECONDITION = 25;
  int EFFECT = 26;
  int PREFERENCE = 27;
  int WHEN = 28;
  int DURATIVE_ACTION = 29;
  int DURATION = 30;
  int CONDITION = 31;
  int DERIVED = 32;
  int PROBLEM = 33;
  int P_DOMAIN = 34;
  int OBJECTS = 35;
  int INIT = 36;
  int GOAL = 37;
  int METRIC = 38;
  int METHOD = 39;
  int EXPANSION = 40;
  int TASKS = 41;
  int STRIPS = 42;
  int TYPING = 43;
  int HTN = 44;
  int NEGATIVE_PRECONDITIONS = 45;
  int DISJUNCTIVE_PRECONDITIONS = 46;
  int EQUALITY = 47;
  int EXISTENTIAL_PRECONDITIONS = 48;
  int UNIVERSAL_PRECONDITIONS = 49;
  int QUANTIFIED_PRECONDITIONS = 50;
  int CONDITIONAL_EFFECTS = 51;
  int ACTION_COSTS = 52;
  int FLUENTS = 53;
  int NUMERIC_FLUENTS = 54;
  int OBJECT_FLUENTS = 55;
  int GOAL_UTILITIES = 56;
  int ADL = 57;
  int DURATIVE_ACTIONS = 58;
  int DERIVED_PREDICATES = 59;
  int TIMED_INITIAL_LITERALS = 60;
  int PREFERENCES = 61;
  int CONSTRAINTS = 62;
  int CONTINUS_EFFECTS = 63;
  int DURATION_INEQUALITIES = 64;
  int GREATER = 65;
  int LESS = 66;
  int GEQUAL = 67;
  int LEQUAL = 68;
  int EQUAL = 69;
  int MUL = 70;
  int DIV = 71;
  int ADD = 72;
  int SUB = 73;
  int ASSIGN = 74;
  int SCALE_UP = 75;
  int SCALE_DOWN = 76;
  int INCREASE = 77;
  int DECREASE = 78;
  int OR = 79;
  int AND = 80;
  int IMPLY = 81;
  int NOT = 82;
  int FORALL = 83;
  int EXISTS = 84;
  int ALWAYS = 85;
  int SOMETIME = 86;
  int WITHIN = 87;
  int AT_MOST_ONCE = 88;
  int SOMETIME_AFTER = 89;
  int SOMETIME_BEFORE = 90;
  int ALWAYS_WITHIN = 91;
  int HOLD_DURING = 92;
  int HOLD_AFTER = 93;
  int AT = 94;
  int START = 95;
  int END = 96;
  int OVER = 97;
  int ALL = 98;
  int TOTAL_TIME = 99;
  int TOTAL_COST = 100;
  int MAXIMIZE = 101;
  int MINIMIZE = 102;
  int IS_VIOLATED = 103;
  int BEFORE = 104;
  int AFTER = 105;
  int BETWEEN = 106;
  int SERIES = 107;
  int TAG = 108;
  int FIRST = 109;
  int LAST = 110;
  int VAR_DURATION = 111;
  int CONTINUOUS_VARIABLE = 112;
  int NUMBER_TYPE = 113;
  int OBJECT_TYPE = 114;
  int VARIABLE_SYMBOL = 115;
  int SYMBOL = 116;
  int NUMBER = 117;
  int DIGIT = 118;
  int LETTER = 119;
  int SEPARATOR = 120;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"//\"",
    "\";\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"(\"",
    "\")\"",
    "\"define\"",
    "\"domain\"",
    "\":requirements\"",
    "\":types\"",
    "\"either\"",
    "\":constants\"",
    "\":predicates\"",
    "\":functions\"",
    "\":action\"",
    "\":parameters\"",
    "\":precondition\"",
    "\":effect\"",
    "\"preference\"",
    "\"when\"",
    "\":durative-action\"",
    "\":duration\"",
    "\":condition\"",
    "\":derived\"",
    "\"problem\"",
    "\":domain\"",
    "\":objects\"",
    "\":init\"",
    "\":goal\"",
    "\":metric\"",
    "\":method\"",
    "\":expansion\"",
    "\":tasks\"",
    "\":strips\"",
    "\":typing\"",
    "\":htn\"",
    "\":negative-preconditions\"",
    "\":disjunctive-preconditions\"",
    "\":equality\"",
    "\":existential-preconditions\"",
    "\":universal-preconditions\"",
    "\":quantified-preconditions\"",
    "\":conditional-effects\"",
    "\":action-costs\"",
    "\":fluents\"",
    "\":numeric-fluents\"",
    "\":object-fluents\"",
    "\":goal-utilities\"",
    "\":adl\"",
    "\":durative-actions\"",
    "\":derived-predicates\"",
    "\":timed-initial-literals\"",
    "\":preferences\"",
    "\":constraints\"",
    "\":continus-effects\"",
    "\":duration-inequalities\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"=\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"assign\"",
    "\"scale-up\"",
    "\"scale-down\"",
    "\"increase\"",
    "\"decrease\"",
    "\"or\"",
    "\"and\"",
    "\"imply\"",
    "\"not\"",
    "\"forall\"",
    "\"exists\"",
    "\"always\"",
    "\"sometime\"",
    "\"within\"",
    "\"at-most-once\"",
    "\"sometime-after\"",
    "\"sometime-before\"",
    "\"always-within\"",
    "\"hold-during\"",
    "\"hold-after\"",
    "\"at\"",
    "\"start\"",
    "\"end\"",
    "\"over\"",
    "\"all\"",
    "\"total-time\"",
    "\"total-cost\"",
    "\"maximize\"",
    "\"minimize\"",
    "\"is-violated\"",
    "\"before\"",
    "\"after\"",
    "\"between\"",
    "\"series\"",
    "\"tag\"",
    "\"first\"",
    "\"last\"",
    "\"?duration\"",
    "\"#t\"",
    "\"number\"",
    "\"object\"",
    "<VARIABLE_SYMBOL>",
    "<SYMBOL>",
    "<NUMBER>",
    "<DIGIT>",
    "<LETTER>",
    "<SEPARATOR>",
  };

}
