/* Generated By:JavaCC: Do not edit this line. LexerConstants.java */
package core.planner.lexer;

public interface LexerConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int DEFDOMAIN = 13;
  int DEFPROBLEM = 14;
  int NOT = 15;
  int CALL = 16;
  int INVARIANT_CALL = 17;
  int LIST = 18;
  int FIRST = 19;
  int OPERATOR = 20;
  int METHOD = 21;
  int LPAREN = 22;
  int RPAREN = 23;
  int DOT = 24;
  int AXIOM = 25;
  int SUP = 26;
  int INF = 27;
  int SUP_EQUAL = 28;
  int INF_EQUAL = 29;
  int MULT = 30;
  int DIV = 31;
  int PLUS = 32;
  int MINUS = 33;
  int EQUAL = 34;
  int NOT_EQUAL = 35;
  int MEMBER = 36;
  int MIN = 37;
  int MAX = 38;
  int CAT = 39;
  int SYMBOL = 40;
  int VARIABLE_SYMBOL = 41;
  int INVARIANT_SYMBOL = 42;
  int PRIMITIVE_TASK_SYMBOL = 43;
  int NUMBER = 44;
  int DIGIT = 45;
  int LETTER = 46;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"//\"",
    "\";\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"defdomain\"",
    "\"defproblem\"",
    "\"not\"",
    "\"call\"",
    "\"~call\"",
    "\"list\"",
    "\":first\"",
    "\":operator\"",
    "\":method\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\":-\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "\"!=\"",
    "\"member\"",
    "\"min\"",
    "\"max\"",
    "\"cat\"",
    "<SYMBOL>",
    "<VARIABLE_SYMBOL>",
    "<INVARIANT_SYMBOL>",
    "<PRIMITIVE_TASK_SYMBOL>",
    "<NUMBER>",
    "<DIGIT>",
    "<LETTER>",
  };

}
