/* Generated By:JavaCC: Do not edit this line. Lexer.java */
package core.planner.lexer;

import core.planner.*;
import java.io.*;

public class Lexer implements LexerConstants {
        /**
	* Create a <tt>Lexer</tt> from a specific <tt>InputStream<tt>.
	* @param stream the file <tt>InputStream</tt>.
	*/
        public Lexer(InputStream stream, boolean debug) {
                this(stream);
        }

/**
* Read an AgentDescription from the input stream.
* @return the AgentDescription read.
*/
  final public AgentDescription agentDescription() throws ParseException {
        AgentDescription agentDescription = new AgentDescription();
        Problem problem = new Problem();
        Domain domain = new Domain();
    domain = domain();
                         agentDescription.setDomain(domain);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAREN:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      problem = problem();
                agentDescription.addProblem(problem);
    }
         {if (true) return agentDescription;}
    throw new Error("Missing return statement in function");
  }

/**
* Read a list of problems from the input stream.
* @return the ProblemSet read.
*/
  final public ProblemSet problemSet() throws ParseException {
        ProblemSet problemSet = new ProblemSet();
        Problem problem = new Problem();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAREN:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      problem = problem();
                if (!problemSet.add(problem)) {
                                {if (true) throw new ParseException("Problem " + problem.getName() + " line: " +
                                        getNextToken().beginLine + " column: " +
                                        getNextToken().beginColumn+" already defined.\n");}
                }
    }
         {if (true) return problemSet;}
    throw new Error("Missing return statement in function");
  }

/**
* Read a problem from the input stream.
* @return the problem read.
*/
  final public Problem problem() throws ParseException {
        Problem problem = new Problem();
        State state;
        TaskList tasks;
        Token token;
    jj_consume_token(LPAREN);
    jj_consume_token(DEFPROBLEM);
    token = jj_consume_token(SYMBOL);
                                problem.setName(token.image);
    token = jj_consume_token(SYMBOL);
                                problem.setDomainName(token.image);
    state = state();
                               problem.setState(state);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LPAREN:
    case SYMBOL:
      tasks = taskList();
                                   problem.setTasks(tasks);
      break;
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
                {if (true) return problem;}
    throw new Error("Missing return statement in function");
  }

/**
* Read a State from the input stream.
* @return the State read.
*/
  final public State state() throws ParseException {
        Token token;
        Term t;
        Literal literal;
        State state;
    if (jj_2_1(2147483647)) {
      token = jj_consume_token(SYMBOL);
                        if (token.image.equals("nil")) {
                                {if (true) return new State();}
                        }
                        else {
                                {if (true) throw new ParseException("Expected \"nil\" line: "+
                                        token.beginLine + " column: "+
                                        token.beginColumn + "\n");}
                        }
    } else if (jj_2_2(2147483647)) {
                 state = new State();
      jj_consume_token(LPAREN);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LPAREN:
        case SYMBOL:
        case VARIABLE_SYMBOL:
        case NUMBER:
          ;
          break;
        default:
          jj_la1[3] = jj_gen;
          break label_3;
        }
        literal = literal();
                        if (!state.add(literal)) {
                                {if (true) throw new ParseException("Literal " + literal + " line: "+
                                        getNextToken().beginLine + " column: " +
                                        getNextToken().beginColumn+" already defined.\n");}
                        }
      }
      jj_consume_token(RPAREN);
                          {if (true) return state;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
* Read a Domain from the input stream.
* @return the Domain read.
*/
  final public Domain domain() throws ParseException {
        Domain domain = new Domain();
        Axiom axiom;
        AxiomSet axioms = new AxiomSet();
        Operator operator;
        OperatorSet operators = new OperatorSet();
        Method method;
        MethodSet methods = new MethodSet();
        Token token;
    jj_consume_token(LPAREN);
    jj_consume_token(DEFDOMAIN);
    token = jj_consume_token(SYMBOL);
    jj_consume_token(LPAREN);
                domain.setName(token.image);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAREN:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_4;
      }
      if (jj_2_3(2)) {
        axiom = axiom();
                        axiom.setName("Axiom_"+(axioms.size()+1)+"_");
                        if (!axioms.add(axiom)) {
                                {if (true) throw new ParseException("Axiom " + axiom.getHead() + " line: " +
                                        getNextToken().beginLine + " column: " +
                                        getNextToken().beginColumn+" already defined.\n");}
                        }
      } else if (jj_2_4(2)) {
        operator = operator();
                        if (!operators.add(operator)) {
                                {if (true) throw new ParseException("Operator " + operator.getHead() + " line: " +
                                        getNextToken().beginLine + " column: " +
                                        getNextToken().beginColumn + " already defined.\n");}
                        }
      } else if (jj_2_5(2)) {
        method = method();
                        method.setName("Method_"+(methods.size()+1)+"_");
                        if (!methods.add(method)) {
                                {if (true) throw new ParseException("Method " + method.getHead() + " line: " +
                                        getNextToken().beginLine + " column: " +
                                        getNextToken().beginColumn + " already defined.\n");}
                        }
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(RPAREN);
    jj_consume_token(RPAREN);
                domain.setAxioms(axioms);
                domain.setOperators(operators);
                domain.setMethods(methods);
                {if (true) return domain;}
    throw new Error("Missing return statement in function");
  }

/**
* Read an Operator from the input stream.
* @return the Operator read.
*/
  final public Operator operator() throws ParseException {
        TaskAtom head;
        Conjunction precondition;
        Conjunction delEffect;
        Conjunction addEffect;
        double cost = 1;
        Token token;
    jj_consume_token(LPAREN);
    jj_consume_token(OPERATOR);
    head = taskAtom();
    precondition = conjunction();
    delEffect = conjunction();
    addEffect = conjunction();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMBER:
      token = jj_consume_token(NUMBER);
                                 cost = Double.parseDouble(token.image);
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
                Operator operator = new Operator();
                operator.setHead(head);
                operator.setPreconditions(precondition);
                operator.setDelEffects(delEffect);
                operator.setAddEffects(addEffect);
                operator.setCost(cost);
                {if (true) return operator;}
    throw new Error("Missing return statement in function");
  }

/**
* Read a Method from the input stream.
* @return the Method read.
*/
  final public Method method() throws ParseException {
        TaskAtom head;
        DecompositionList tail;
    jj_consume_token(LPAREN);
    jj_consume_token(METHOD);
    head = taskAtom();
    tail = decompositionList();
    jj_consume_token(RPAREN);
                Method method = new Method();
                method.setHead(head);
                method.setTail(tail);
                {if (true) return method;}
    throw new Error("Missing return statement in function");
  }

/**
* Read a DecompositionList from the input stream.
* @return the DecompositionList read.
*/
  final public DecompositionList decompositionList() throws ParseException {
        int index = 1;
        Decomposition decomposition;
        DecompositionList decompositionList = new DecompositionList();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAREN:
      case SYMBOL:
      case VARIABLE_SYMBOL:
      case NUMBER:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_5;
      }
      decomposition = decompositionName(index);
                decompositionList.add(decomposition);
                index++;
    }
         {if (true) return decompositionList;}
    throw new Error("Missing return statement in function");
  }

/**
* Read a Decomposition at a specific index from the input stream.
* @param index the index of the Decomposition.
* @return the Decomposition read.
*/
  final public Decomposition decompositionName(int index) throws ParseException {
        Token token;
        String name;
        Decomposition decomposition;
    if (jj_2_6(2147483647)) {
      token = jj_consume_token(SYMBOL);
                                name = token.image;
      decomposition = decomposition();
                        decomposition.setName("Part_"+index);
                        {if (true) return decomposition;}
    } else if (jj_2_7(2147483647)) {
      decomposition = decomposition();
                        decomposition.setName("Part_"+index);
                        {if (true) return  decomposition;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
* Read a Decomposition from the input stream.
* @return the Decomposition read.
*/
  final public Decomposition decomposition() throws ParseException {
        Conjunction precondition;
        TaskList tasks;
        boolean isFirst = false;
    if (jj_2_8(2147483647)) {
                                      isFirst = true;
      precondition = conjunction();
      tasks = taskList();
                Decomposition decomposition = new Decomposition();
                decomposition.setFirst(isFirst);
                decomposition.setPreconditions(precondition);
                decomposition.setTasks(tasks);
                {if (true) return decomposition;}
    } else if (jj_2_9(2147483647)) {
                              isFirst = false;
      precondition = conjunction();
      tasks = taskList();
                Decomposition decomposition = new Decomposition();
                decomposition.setFirst(isFirst);
                decomposition.setPreconditions(precondition);
                decomposition.setTasks(tasks);
                {if (true) return decomposition;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
* Read a TaskList from the input stream.
* @return the TaskList read.
*/
  final public TaskList taskList() throws ParseException {
        Token token;
        TaskAtom taskAtom;
        TaskList tasks = new TaskList();
    if (jj_2_10(2147483647)) {
      token = jj_consume_token(SYMBOL);
                        if (token.image.equals("nil")) {
                                {if (true) return tasks;}
                        }
                        else {
                                {if (true) throw new ParseException("Expected \"nil\" line: "+
                                        token.beginLine+" column: "+
                                        token.beginColumn+"\n");}
                        }
    } else if (jj_2_11(2147483647)) {
      token = jj_consume_token(LPAREN);
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LPAREN:
          ;
          break;
        default:
          jj_la1[7] = jj_gen;
          break label_6;
        }
        taskAtom = taskAtom();
                                tasks.add(taskAtom);
      }
      jj_consume_token(RPAREN);
                          {if (true) return tasks;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
* Read a TaskAtom from the input stream.
* @return the TaskAtom read.
*/
  final public TaskAtom taskAtom() throws ParseException {
        Token token;
        Term term;
        TaskAtom taskAtom;
    if (jj_2_12(2147483647)) {
      jj_consume_token(LPAREN);
      token = jj_consume_token(PRIMITIVE_TASK_SYMBOL);
                                taskAtom = new TaskAtom(token.image);
                                taskAtom.setPrimitive(true);
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LPAREN:
        case SYMBOL:
        case VARIABLE_SYMBOL:
        case NUMBER:
          ;
          break;
        default:
          jj_la1[8] = jj_gen;
          break label_7;
        }
        term = term();
                                      taskAtom.add(term);
      }
      jj_consume_token(RPAREN);
                          {if (true) return taskAtom;}
    } else if (jj_2_13(2147483647)) {
      jj_consume_token(LPAREN);
      token = jj_consume_token(SYMBOL);
                                taskAtom = new TaskAtom(token.image);
                                taskAtom.setCompound(true);
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LPAREN:
        case SYMBOL:
        case VARIABLE_SYMBOL:
        case NUMBER:
          ;
          break;
        default:
          jj_la1[9] = jj_gen;
          break label_8;
        }
        term = term();
                                taskAtom.add(term);
      }
      jj_consume_token(RPAREN);
                          {if (true) return taskAtom;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
* Read a Axiom from the input stream.
* @return the Axiom read.
*/
  final public Axiom axiom() throws ParseException {
        Literal head;
        ConjunctionList tail;
    jj_consume_token(LPAREN);
    jj_consume_token(AXIOM);
    head = literal();
    tail = conjunctionList();
    jj_consume_token(RPAREN);
                Axiom axiom = new Axiom();
                axiom.setHead(head);
                axiom.setTail(tail);
                {if (true) return axiom;}
    throw new Error("Missing return statement in function");
  }

/**
* Read a ConjunctionList from the input stream.
* @return the ConjunctionList read.
*/
  final public ConjunctionList conjunctionList() throws ParseException {
        int index = 1;
        Conjunction conjunction;
        ConjunctionList conjunctionList = new ConjunctionList();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAREN:
      case SYMBOL:
      case VARIABLE_SYMBOL:
      case NUMBER:
        ;
        break;
      default:
        jj_la1[10] = jj_gen;
        break label_9;
      }
      conjunction = conjunctionName(index);
                conjunctionList.add(conjunction);
                index++;
    }
         {if (true) return conjunctionList;}
    throw new Error("Missing return statement in function");
  }

/**
* Read a Conjunction at a specific index from the input stream.
* @param index the index of the Conjunction.
* @return the Conjunction read.
*/
  final public Conjunction conjunctionName(int index) throws ParseException {
        Token token;
        String name;
        Conjunction conjunction;
    if (jj_2_14(2147483647)) {
      token = jj_consume_token(SYMBOL);
                                name = token.image;
      conjunction = conjunction();
                        conjunction.setName("Part_"+name);
                        {if (true) return conjunction;}
    } else if (jj_2_15(2147483647)) {
      conjunction = conjunction();
                        conjunction.setName("Part_"+index);
                        {if (true) return  conjunction;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
* Read a Conjunction from the input stream.
* @return the Conjunction read.
*/
  final public Conjunction conjunction() throws ParseException {
        Token token;
        Term t;
        Literal literal;
        Conjunction conjunction;
    if (jj_2_16(2147483647)) {
      token = jj_consume_token(SYMBOL);
                        if (token.image.equals("nil")) {
                                {if (true) return new Conjunction();}
                        }
                        else {
                                {if (true) throw new ParseException("Expected \"nil\" line: "+
                                        token.beginLine+" column: "+
                                        token.beginColumn+"\n");}
                        }
    } else if (jj_2_17(2147483647)) {
      t = term();
                        conjunction = new Conjunction();
                        literal = new Literal();
                        literal.add(t);
                        conjunction.add(literal);
                        conjunction.setVarList(true);
                        {if (true) return conjunction;}
    } else if (jj_2_18(2147483647)) {
                 conjunction = new Conjunction();
      jj_consume_token(LPAREN);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FIRST:
        token = jj_consume_token(FIRST);
                                        conjunction.setLabel(token.image);
        break;
      default:
        jj_la1[11] = jj_gen;
        ;
      }
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LPAREN:
        case SYMBOL:
        case VARIABLE_SYMBOL:
        case NUMBER:
          ;
          break;
        default:
          jj_la1[12] = jj_gen;
          break label_10;
        }
        literal = literal();
                        conjunction.add(literal);
      }
      jj_consume_token(RPAREN);
                          {if (true) return conjunction;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
* Read a Literal from the input stream.
* @return the Literal read.
*/
  final public Literal literal() throws ParseException {
        Token token;
        Literal literal;
    if (jj_2_19(2147483647)) {
      jj_consume_token(LPAREN);
      jj_consume_token(NOT);
      literal = logicalAtom();
      jj_consume_token(RPAREN);
                        literal.setNegative(true);
                        {if (true) return literal;}
    } else if (jj_2_20(2147483647)) {
      literal = logicalAtom();
                {if (true) return literal;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
* Read a LogicalAtom from the input stream.
* @return the LogicalAtom read.
*/
  final public Literal logicalAtom() throws ParseException {
        Token token;
        Literal logicalAtom;
        Term term;
    if (jj_2_21(2147483647)) {
      term = term();
                        logicalAtom = new Literal("call");
                        logicalAtom.add(term);
                        {if (true) return logicalAtom;}
    } else if (jj_2_22(2147483647)) {
      term = term();
                        logicalAtom = new Literal("call");
                        logicalAtom.add(term);
                        logicalAtom.setHypothetical(true);
                        {if (true) return logicalAtom;}
    } else if (jj_2_23(2147483647)) {
      jj_consume_token(LPAREN);
      token = jj_consume_token(SYMBOL);
                                logicalAtom = new Literal(token.image);
      label_11:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LPAREN:
        case SYMBOL:
        case VARIABLE_SYMBOL:
        case NUMBER:
          ;
          break;
        default:
          jj_la1[13] = jj_gen;
          break label_11;
        }
        term = term();
                                logicalAtom.add(term);
      }
      jj_consume_token(RPAREN);
                        {if (true) return logicalAtom;}
    } else if (jj_2_24(2147483647)) {
      jj_consume_token(LPAREN);
      token = jj_consume_token(INVARIANT_SYMBOL);
                                logicalAtom = new Literal(token.image.substring(1, token.image.length()));
                                logicalAtom.setHypothetical(true);
      label_12:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LPAREN:
        case SYMBOL:
        case VARIABLE_SYMBOL:
        case NUMBER:
          ;
          break;
        default:
          jj_la1[14] = jj_gen;
          break label_12;
        }
        term = term();
                                logicalAtom.add(term);
      }
      jj_consume_token(RPAREN);
                        {if (true) return logicalAtom;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
* Read a Term from the input stream.
* @return the Term read.
*/
  final public Term term() throws ParseException {
        Token token;
        Term term;
    if (jj_2_25(2147483647)) {
      term = variable();
                        {if (true) return term;}
    } else if (jj_2_26(2147483647)) {
      term = constant();
                        {if (true) return term;}
    } else if (jj_2_27(2147483647)) {
      term = listTerm();
                        {if (true) return term;}
    } else if (jj_2_28(2147483647)) {
      term = callTerm();
                        {if (true) return term;}
    } else if (jj_2_29(2147483647)) {
      term = callTerm();
                        ((Function)term).setHypothetical(true);
                        {if (true) return term;}
    } else if (jj_2_30(2147483647)) {
      term = function();
                        {if (true) return term;}
    } else if (jj_2_31(2147483647)) {
      term = function();
                        {if (true) return term;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
* Read a Variable from the input stream.
* @return the Variable read.
*/
  final public Variable variable() throws ParseException {
        Token token;
    token = jj_consume_token(VARIABLE_SYMBOL);
                {if (true) return new Variable(token.image);}
    throw new Error("Missing return statement in function");
  }

/**
* Read a Constant from the input stream.
* @return the Constant read.
*/
  final public Constant constant() throws ParseException {
        Token token;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SYMBOL:
      token = jj_consume_token(SYMBOL);
                {if (true) return  new Constant(token.image);}
      break;
    case NUMBER:
      token = jj_consume_token(NUMBER);
                Constant constant = new Constant(token.image);
                constant.setNumerical(true);
                {if (true) return constant;}
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
* Read a list-term from the input stream.
* @return the list-term read.
*/
  final public Term listTerm() throws ParseException {
        Token token;
        Function function;
        Term term;
    if (jj_2_32(3)) {
      jj_consume_token(LPAREN);
      jj_consume_token(LIST);
      jj_consume_token(RPAREN);
                {if (true) return new Constant("nil");}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAREN:
        jj_consume_token(LPAREN);
        jj_consume_token(LIST);
        term = term();
                function = new Function(".");
                function.add(term);
                if (term instanceof Variable) function.setGround(false);
        term = list();
                function.add(term);
                if (term instanceof Variable) {
                        function.setGround(false);
                }
                {if (true) return function;}
        break;
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

/**
* Read a list of terms in a list-term from the input stream.
* @return the term representing the list of term read.
*/
  final public Term list() throws ParseException {
        Token token;
        Term term;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RPAREN:
      jj_consume_token(RPAREN);
                {if (true) return new Constant("nil");}
      break;
    case DOT:
      jj_consume_token(DOT);
      term = term();
      jj_consume_token(RPAREN);
                if (term instanceof Variable
                        || term.getSymbol().equalsIgnoreCase("nil")
                        || term.getSymbol().equalsIgnoreCase(".")) {
                        {if (true) return term;}
                }
                else {
                        Function function = new Function(".");
                        function.add(term);
                        if (term instanceof Variable) {
                                function.setGround(false);
                        }
                        Constant nil = new Constant("nil");
                        function.add(nil);
                        {if (true) return function;}
                }
      break;
    case LPAREN:
    case SYMBOL:
    case VARIABLE_SYMBOL:
    case NUMBER:
      term = term();
                Function function = new Function(".");
                function.add(term);
                if (term instanceof Variable) {
                        function.setGround(false);
                }
      term = list();
                function.add(term);
                {if (true) return function;}
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
* Read a call-term from the input stream.
* @return the call-term read.
*/
  final public Function callTerm() throws ParseException {
        Token token;
        Term term;
        Function function;
    if (jj_2_33(2147483647)) {
      jj_consume_token(LPAREN);
      token = jj_consume_token(CALL);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SUP:
        token = jj_consume_token(SUP);
        break;
      case INF:
        token = jj_consume_token(INF);
        break;
      case SUP_EQUAL:
        token = jj_consume_token(SUP_EQUAL);
        break;
      case INF_EQUAL:
        token = jj_consume_token(INF_EQUAL);
        break;
      case MULT:
        token = jj_consume_token(MULT);
        break;
      case DIV:
        token = jj_consume_token(DIV);
        break;
      case PLUS:
        token = jj_consume_token(PLUS);
        break;
      case MINUS:
        token = jj_consume_token(MINUS);
        break;
      case EQUAL:
        token = jj_consume_token(EQUAL);
        break;
      case NOT_EQUAL:
        token = jj_consume_token(NOT_EQUAL);
        break;
      case MIN:
        token = jj_consume_token(MIN);
        break;
      case MAX:
        token = jj_consume_token(MAX);
        break;
      case MEMBER:
        token = jj_consume_token(MEMBER);
        break;
      case CAT:
        token = jj_consume_token(CAT);
        break;
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                        function = new Function(token.image);
                        function.setEval(true);
      term = term();
                        function.add(term);
                        if (term instanceof Variable) {
                                function.setGround(false);
                        }
      term = term();
                        function.add(term);
                        if (term instanceof Variable) {
                                function.setGround(false);
                        }
      jj_consume_token(RPAREN);
                {if (true) return function;}
    } else if (jj_2_34(2147483647)) {
      jj_consume_token(LPAREN);
      token = jj_consume_token(INVARIANT_CALL);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SUP:
        token = jj_consume_token(SUP);
        break;
      case INF:
        token = jj_consume_token(INF);
        break;
      case SUP_EQUAL:
        token = jj_consume_token(SUP_EQUAL);
        break;
      case INF_EQUAL:
        token = jj_consume_token(INF_EQUAL);
        break;
      case EQUAL:
        token = jj_consume_token(EQUAL);
        break;
      case NOT_EQUAL:
        token = jj_consume_token(NOT_EQUAL);
        break;
      case MIN:
        token = jj_consume_token(MIN);
        break;
      case MAX:
        token = jj_consume_token(MAX);
        break;
      case MEMBER:
        token = jj_consume_token(MEMBER);
        break;
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                        function = new Function(token.image);
                        function.setEval(true);
      term = term();
                        function.add(term);
                        if (term instanceof Variable) {
                                function.setGround(false);
                        }
      term = term();
                        function.add(term);
                        if (term instanceof Variable) {
                                function.setGround(false);
                        }
      jj_consume_token(RPAREN);
                {if (true) return function;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
* Read a Function from the input stream.
* @return the Function read.
*/
  final public Function function() throws ParseException {
        Token token;
        Term term;
        Function function;
    if (jj_2_35(2147483647)) {
      jj_consume_token(LPAREN);
      token = jj_consume_token(SYMBOL);
                                function = new Function(token.image);
      label_13:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LPAREN:
        case SYMBOL:
        case VARIABLE_SYMBOL:
        case NUMBER:
          ;
          break;
        default:
          jj_la1[20] = jj_gen;
          break label_13;
        }
        term = term();
                                function.add(term);
                                if (term instanceof Variable) {
                                        function.setGround(false);
                                }
      }
      jj_consume_token(RPAREN);
                        {if (true) return function;}
    } else if (jj_2_36(2147483647)) {
      jj_consume_token(LPAREN);
      token = jj_consume_token(INVARIANT_SYMBOL);
                                function = new Function(token.image.substring(1, token.image.length()));
                                function.setHypothetical(true);
      label_14:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LPAREN:
        case SYMBOL:
        case VARIABLE_SYMBOL:
        case NUMBER:
          ;
          break;
        default:
          jj_la1[21] = jj_gen;
          break label_14;
        }
        term = term();
                                function.add(term);
                                if (term instanceof Variable) {
                                        function.setGround(false);
                                }
      }
      jj_consume_token(RPAREN);
                        {if (true) return function;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  final private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  final private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  final private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  final private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  final private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  final private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  final private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  final private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  final private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  final private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  final private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  final private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  final private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  final private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  final private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  final private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  final private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  final private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  final private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  final private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  final private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  final private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  final private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  final private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  final private boolean jj_2_26(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_26(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  final private boolean jj_2_27(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_27(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(26, xla); }
  }

  final private boolean jj_2_28(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_28(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(27, xla); }
  }

  final private boolean jj_2_29(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_29(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(28, xla); }
  }

  final private boolean jj_2_30(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_30(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(29, xla); }
  }

  final private boolean jj_2_31(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_31(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(30, xla); }
  }

  final private boolean jj_2_32(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_32(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(31, xla); }
  }

  final private boolean jj_2_33(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_33(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(32, xla); }
  }

  final private boolean jj_2_34(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_34(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(33, xla); }
  }

  final private boolean jj_2_35(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_35(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(34, xla); }
  }

  final private boolean jj_2_36(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_36(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(35, xla); }
  }

  final private boolean jj_3R_24() {
    if (jj_3R_31()) return true;
    return false;
  }

  final private boolean jj_3_16() {
    if (jj_scan_token(SYMBOL)) return true;
    return false;
  }

  final private boolean jj_3R_19() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) return true;
    }
    }
    return false;
  }

  final private boolean jj_3R_23() {
    if (jj_scan_token(SYMBOL)) return true;
    return false;
  }

  final private boolean jj_3R_57() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(LIST)) return true;
    if (jj_3R_31()) return true;
    if (jj_3R_64()) return true;
    return false;
  }

  final private boolean jj_3_32() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(LIST)) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  final private boolean jj_3R_49() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_32()) {
    jj_scanpos = xsp;
    if (jj_3R_57()) return true;
    }
    return false;
  }

  final private boolean jj_3_15() {
    if (jj_3R_19()) return true;
    return false;
  }

  final private boolean jj_3_14() {
    if (jj_scan_token(SYMBOL)) return true;
    if (jj_3R_19()) return true;
    return false;
  }

  final private boolean jj_3R_56() {
    if (jj_scan_token(NUMBER)) return true;
    return false;
  }

  final private boolean jj_3R_17() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(METHOD)) return true;
    return false;
  }

  final private boolean jj_3R_55() {
    if (jj_scan_token(SYMBOL)) return true;
    return false;
  }

  final private boolean jj_3R_48() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_55()) {
    jj_scanpos = xsp;
    if (jj_3R_56()) return true;
    }
    return false;
  }

  final private boolean jj_3R_66() {
    if (jj_3R_31()) return true;
    return false;
  }

  final private boolean jj_3R_47() {
    if (jj_scan_token(VARIABLE_SYMBOL)) return true;
    return false;
  }

  final private boolean jj_3_31() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(INVARIANT_SYMBOL)) return true;
    return false;
  }

  final private boolean jj_3_36() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(INVARIANT_SYMBOL)) return true;
    return false;
  }

  final private boolean jj_3R_65() {
    if (jj_3R_31()) return true;
    return false;
  }

  final private boolean jj_3_30() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(SYMBOL)) return true;
    return false;
  }

  final private boolean jj_3R_16() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(OPERATOR)) return true;
    return false;
  }

  final private boolean jj_3_29() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(INVARIANT_CALL)) return true;
    return false;
  }

  final private boolean jj_3R_44() {
    if (jj_3R_51()) return true;
    return false;
  }

  final private boolean jj_3R_61() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(INVARIANT_SYMBOL)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_66()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  final private boolean jj_3_28() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(CALL)) return true;
    return false;
  }

  final private boolean jj_3R_43() {
    if (jj_3R_51()) return true;
    return false;
  }

  final private boolean jj_3_35() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(SYMBOL)) return true;
    return false;
  }

  final private boolean jj_3R_68() {
    if (jj_3R_31()) return true;
    return false;
  }

  final private boolean jj_3_27() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(LIST)) return true;
    return false;
  }

  final private boolean jj_3R_15() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(AXIOM)) return true;
    return false;
  }

  final private boolean jj_3R_42() {
    if (jj_3R_50()) return true;
    return false;
  }

  final private boolean jj_3_26() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(40)) {
    jj_scanpos = xsp;
    if (jj_scan_token(44)) return true;
    }
    return false;
  }

  final private boolean jj_3R_41() {
    if (jj_3R_50()) return true;
    return false;
  }

  final private boolean jj_3R_67() {
    if (jj_3R_31()) return true;
    return false;
  }

  final private boolean jj_3R_60() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(SYMBOL)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_65()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  final private boolean jj_3R_51() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_60()) {
    jj_scanpos = xsp;
    if (jj_3R_61()) return true;
    }
    return false;
  }

  final private boolean jj_3_25() {
    if (jj_scan_token(VARIABLE_SYMBOL)) return true;
    return false;
  }

  final private boolean jj_3R_40() {
    if (jj_3R_49()) return true;
    return false;
  }

  final private boolean jj_3_5() {
    if (jj_3R_17()) return true;
    return false;
  }

  final private boolean jj_3_13() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(SYMBOL)) return true;
    return false;
  }

  final private boolean jj_3R_39() {
    if (jj_3R_48()) return true;
    return false;
  }

  final private boolean jj_3R_31() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) return true;
    }
    }
    }
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_38() {
    if (jj_3R_47()) return true;
    return false;
  }

  final private boolean jj_3_4() {
    if (jj_3R_16()) return true;
    return false;
  }

  final private boolean jj_3R_35() {
    if (jj_3R_31()) return true;
    return false;
  }

  final private boolean jj_3_12() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(PRIMITIVE_TASK_SYMBOL)) return true;
    return false;
  }

  final private boolean jj_3R_63() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(SYMBOL)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_68()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  final private boolean jj_3_3() {
    if (jj_3R_15()) return true;
    return false;
  }

  final private boolean jj_3R_46() {
    if (jj_3R_54()) return true;
    return false;
  }

  final private boolean jj_3R_62() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(PRIMITIVE_TASK_SYMBOL)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_67()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  final private boolean jj_3R_54() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_62()) {
    jj_scanpos = xsp;
    if (jj_3R_63()) return true;
    }
    return false;
  }

  final private boolean jj_3R_34() {
    if (jj_3R_31()) return true;
    return false;
  }

  final private boolean jj_3_24() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(INVARIANT_SYMBOL)) return true;
    return false;
  }

  final private boolean jj_3_34() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(INVARIANT_CALL)) return true;
    return false;
  }

  final private boolean jj_3_11() {
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  final private boolean jj_3R_59() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(INVARIANT_CALL)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(26)) {
    jj_scanpos = xsp;
    if (jj_scan_token(27)) {
    jj_scanpos = xsp;
    if (jj_scan_token(28)) {
    jj_scanpos = xsp;
    if (jj_scan_token(29)) {
    jj_scanpos = xsp;
    if (jj_scan_token(34)) {
    jj_scanpos = xsp;
    if (jj_scan_token(35)) {
    jj_scanpos = xsp;
    if (jj_scan_token(37)) {
    jj_scanpos = xsp;
    if (jj_scan_token(38)) {
    jj_scanpos = xsp;
    if (jj_scan_token(36)) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    if (jj_3R_31()) return true;
    if (jj_3R_31()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  final private boolean jj_3R_29() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(INVARIANT_SYMBOL)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_35()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  final private boolean jj_3_23() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(SYMBOL)) return true;
    return false;
  }

  final private boolean jj_3R_37() {
    if (jj_scan_token(LPAREN)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_46()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  final private boolean jj_3_10() {
    if (jj_scan_token(SYMBOL)) return true;
    return false;
  }

  final private boolean jj_3_22() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(INVARIANT_CALL)) return true;
    return false;
  }

  final private boolean jj_3R_28() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(SYMBOL)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_34()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  final private boolean jj_3_21() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(CALL)) return true;
    return false;
  }

  final private boolean jj_3_33() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(CALL)) return true;
    return false;
  }

  final private boolean jj_3_2() {
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  final private boolean jj_3R_30() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) return true;
    }
    return false;
  }

  final private boolean jj_3R_36() {
    if (jj_scan_token(SYMBOL)) return true;
    return false;
  }

  final private boolean jj_3R_27() {
    if (jj_3R_31()) return true;
    return false;
  }

  final private boolean jj_3R_58() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(CALL)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(26)) {
    jj_scanpos = xsp;
    if (jj_scan_token(27)) {
    jj_scanpos = xsp;
    if (jj_scan_token(28)) {
    jj_scanpos = xsp;
    if (jj_scan_token(29)) {
    jj_scanpos = xsp;
    if (jj_scan_token(30)) {
    jj_scanpos = xsp;
    if (jj_scan_token(31)) {
    jj_scanpos = xsp;
    if (jj_scan_token(32)) {
    jj_scanpos = xsp;
    if (jj_scan_token(33)) {
    jj_scanpos = xsp;
    if (jj_scan_token(34)) {
    jj_scanpos = xsp;
    if (jj_scan_token(35)) {
    jj_scanpos = xsp;
    if (jj_scan_token(37)) {
    jj_scanpos = xsp;
    if (jj_scan_token(38)) {
    jj_scanpos = xsp;
    if (jj_scan_token(36)) {
    jj_scanpos = xsp;
    if (jj_scan_token(39)) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    if (jj_3R_31()) return true;
    if (jj_3R_31()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  final private boolean jj_3R_50() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) return true;
    }
    return false;
  }

  final private boolean jj_3R_20() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) return true;
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_26() {
    if (jj_3R_31()) return true;
    return false;
  }

  final private boolean jj_3_1() {
    if (jj_scan_token(SYMBOL)) return true;
    return false;
  }

  final private boolean jj_3_9() {
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  final private boolean jj_3_20() {
    if (jj_3R_20()) return true;
    return false;
  }

  final private boolean jj_3_19() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(NOT)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  final private boolean jj_3_8() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(FIRST)) return true;
    return false;
  }

  final private boolean jj_3R_22() {
    if (jj_3R_19()) return true;
    if (jj_3R_30()) return true;
    return false;
  }

  final private boolean jj_3R_53() {
    if (jj_3R_20()) return true;
    return false;
  }

  final private boolean jj_3R_71() {
    if (jj_3R_31()) return true;
    if (jj_3R_64()) return true;
    return false;
  }

  final private boolean jj_3R_32() {
    if (jj_scan_token(FIRST)) return true;
    return false;
  }

  final private boolean jj_3R_52() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(NOT)) return true;
    if (jj_3R_20()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  final private boolean jj_3R_45() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) return true;
    }
    return false;
  }

  final private boolean jj_3R_18() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_21()) {
    jj_scanpos = xsp;
    if (jj_3R_22()) return true;
    }
    return false;
  }

  final private boolean jj_3R_21() {
    if (jj_3R_19()) return true;
    if (jj_3R_30()) return true;
    return false;
  }

  final private boolean jj_3R_33() {
    if (jj_3R_45()) return true;
    return false;
  }

  final private boolean jj_3_7() {
    if (jj_3R_18()) return true;
    return false;
  }

  final private boolean jj_3_18() {
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  final private boolean jj_3_6() {
    if (jj_scan_token(SYMBOL)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  final private boolean jj_3R_70() {
    if (jj_scan_token(DOT)) return true;
    if (jj_3R_31()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  final private boolean jj_3_17() {
    if (jj_scan_token(VARIABLE_SYMBOL)) return true;
    return false;
  }

  final private boolean jj_3R_69() {
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  final private boolean jj_3R_64() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_69()) {
    jj_scanpos = xsp;
    if (jj_3R_70()) {
    jj_scanpos = xsp;
    if (jj_3R_71()) return true;
    }
    }
    return false;
  }

  final private boolean jj_3R_25() {
    if (jj_scan_token(LPAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_32()) jj_scanpos = xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_33()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  public LexerTokenManager token_source;
  SimpleCharStream jj_input_stream;
  public Token token, jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  public boolean lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[22];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_0();
      jj_la1_1();
   }
   private static void jj_la1_0() {
      jj_la1_0 = new int[] {0x400000,0x400000,0x400000,0x400000,0x400000,0x0,0x400000,0x400000,0x400000,0x400000,0x400000,0x80000,0x400000,0x400000,0x400000,0x0,0x400000,0x1c00000,0xfc000000,0x3c000000,0x400000,0x400000,};
   }
   private static void jj_la1_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x100,0x1300,0x0,0x1000,0x1300,0x0,0x1300,0x1300,0x1300,0x0,0x1300,0x1300,0x1300,0x1100,0x0,0x1300,0xff,0x7c,0x1300,0x1300,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[36];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  public Lexer(java.io.InputStream stream) {
     this(stream, null);
  }
  public Lexer(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new LexerTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(java.io.InputStream stream) {
     ReInit(stream);
  }
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public Lexer(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new LexerTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public Lexer(LexerTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(LexerTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  final private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }

  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  final public Token getToken(int index) {
    Token t = lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.Vector<int[]> jj_expentries = new java.util.Vector<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Enumeration e = jj_expentries.elements(); e.hasMoreElements();) {
        int[] oldentry = (int[])(e.nextElement());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.addElement(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[47];
    for (int i = 0; i < 47; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 22; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 47; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  final public void enable_tracing() {
  }

  final public void disable_tracing() {
  }

  final private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 36; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
            case 26: jj_3_27(); break;
            case 27: jj_3_28(); break;
            case 28: jj_3_29(); break;
            case 29: jj_3_30(); break;
            case 30: jj_3_31(); break;
            case 31: jj_3_32(); break;
            case 32: jj_3_33(); break;
            case 33: jj_3_34(); break;
            case 34: jj_3_35(); break;
            case 35: jj_3_36(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  final private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
