0 :  (Lift hoist0 crate1 pallet0 depot0  )  
1 :  (Drive truck0 distributor1 depot0  )  
2 :  (Load hoist0 crate1 truck0 depot0  )  
3 :  (Drive truck0 depot0 distributor0  )  
4 :  (Lift hoist1 crate0 pallet1 distributor0  )  
5 :  (Load hoist1 crate0 truck0 distributor0  )  
6 :  (Unload hoist1 crate1 truck0 distributor0  )  
7 :  (Drop hoist1 crate1 pallet1 distributor0  )  
8 :  (Drive truck0 distributor0 distributor1  )  
9 :  (Unload hoist2 crate0 truck0 distributor1  )  
10 :  (Drop hoist2 crate0 pallet2 distributor1  )  
