(define (problem BLOCKS-10-0)
(:domain BLOCKS)
     (:requirements :strips :typing :negative-preconditions :htn :equality)

(:objects F I J H E D B A C G - block)
(:INIT 
	(CLEAR C) 
    (CLEAR F) 
    (ONTABLE I) 
    (ONTABLE F) 
    (ON C E) 
    (ON E J) 
    (ON J B)
    (ON B G) 
    (ON G H) 
    (ON H A) 
    (ON A D) 
    (ON D I) 
    (HANDEMPTY))
(:goal
     :tasks  (
            (tag t1 (do_put_on G I))
            (tag t2 (do_put_on A G))
            (tag t3 (do_put_on B A))
            (tag t4 (do_put_on H B))
            (tag t5 (do_put_on E H))
            (tag t6 (do_put_on J E))
            (tag t7 (do_put_on F J))
            (tag t8 (do_put_on C F))
            (tag t9 (do_put_on D C))

        )

    :constraints(and
                    (after (and
                                (ON D C) 
                                (ON C F) 
                                (ON F J) 
                                (ON J E) 
                                (ON E H) 
                                (ON H B) 
                                (ON B A)
                                (ON A G) 
                                (ON G I)
                            ) t1)
                )    
))
