(define (problem BLOCKS-11-1)
(:domain BLOCKS)
     (:requirements :strips :typing :negative-preconditions :htn :equality)

(:objects F I J H E D B A C K G - block)
(:INIT 
	(CLEAR J) 
    (CLEAR F) 
    (CLEAR D) 
    (CLEAR G) 
    (ONTABLE I) 
    (ONTABLE K)
    (ONTABLE H) 
    (ONTABLE A) 
    (ON J I)
    (ON F E) 
    (ON E K) 
    (ON D C) 
    (ON C H) 
    (ON G B)
    (ON B A)
    (HANDEMPTY))
(:goal
     :tasks  (
            (tag t1 (do_put_on I E))
            (tag t2 (do_put_on G I))
            (tag t3 (do_put_on F G))
            (tag t4 (do_put_on C F))
            (tag t5 (do_put_on A C))
            (tag t6 (do_put_on H A))
            (tag t7 (do_put_on K H))
            (tag t8 (do_put_on J K))
            (tag t9 (do_put_on D J))
            (tag t10 (do_put_on B D))

        )

    :constraints(and
                    (after (and
                                (ON B D) 
                                (ON D J) 
                                (ON J K) 
                                (ON K H) 
                                (ON H A) 
                                (ON A C) 
                                (ON C F)
                                (ON F G) 
                                (ON G I) 
                                (ON I E)
                            ) t1)
                )    
))
