(define (problem BLOCKS-14-1)
(:domain BLOCKS)
     (:requirements :strips :typing :negative-preconditions :htn :equality)

(:objects F I G J H N E D B L A C K M  - block)
(:INIT 
	(CLEAR G) 
    (CLEAR C) 
    (CLEAR I) 
    (CLEAR H) 
    (CLEAR N) 
    (ONTABLE J)
     (ONTABLE E) 
     (ONTABLE M) 
     (ONTABLE B) 
     (ONTABLE N) 
     (ON G J) 
     (ON C E) 
     (ON I D)
     (ON D L) 
     (ON L M) 
     (ON H F) 
     (ON F A) 
     (ON A K) 
     (ON K B)
    (HANDEMPTY))
(:goal
     :tasks  (
            (tag t1 (do_put_on N C))
            (tag t2 (do_put_on L N))
            (tag t3 (do_put_on E L))
            (tag t4 (do_put_on I E))
            (tag t5 (do_put_on A I))
            (tag t6 (do_put_on G A))
            (tag t7 (do_put_on F G))
            (tag t8 (do_put_on K F))
            (tag t9 (do_put_on M K))
            (tag t10 (do_put_on H M))
            (tag t11 (do_put_on B H))
            (tag t12 (do_put_on D B))
            (tag t13 (do_put_on J D))

        )

    :constraints(and
                    (after (and
                                (ON J D) 
                                (ON D B) 
                                (ON B H) 
                                (ON H M) 
                                (ON M K) 
                                (ON K F) 
                                (ON F G)
                                (ON G A)
                                (ON A I) 
                                (ON I E) 
                                (ON E L) 
                                (ON L N) 
                                (ON N C)
                            ) t1)
                )    
))
