(define (problem BLOCKS-16-1)
(:domain BLOCKS)
     (:requirements :strips :typing :negative-preconditions :htn :equality)

(:objects F I G O J H N E P D B L A C K M  - block)
(:INIT 
	(CLEAR F) 
    (CLEAR H) 
    (CLEAR O) 
    (ONTABLE A) 
    (ONTABLE E) 
    (ONTABLE G)
    (ON F L) 
    (ON L M) 
    (ON M J) 
    (ON J P) 
    (ON P N) 
    (ON N I) 
    (ON I B) 
    (ON B D)
    (ON D C) 
    (ON C K) 
    (ON K A) 
    (ON H E) 
    (ON O G)
    (HANDEMPTY))
(:goal
     :tasks  (
            (tag t1 (do_put_on C O))
            (tag t2 (do_put_on M C))
            (tag t3 (do_put_on E M))
            (tag t4 (do_put_on N E))
            (tag t5 (do_put_on A N))
            (tag t6 (do_put_on H A))
            (tag t7 (do_put_on J H))
            (tag t8 (do_put_on L J))
            (tag t9 (do_put_on I L))
            (tag t10 (do_put_on K I))
            (tag t11 (do_put_on G K))
            (tag t12 (do_put_on F G))
            (tag t13 (do_put_on P F))
            (tag t14 (do_put_on B P))
            (tag t15 (do_put_on D B))
        )

    :constraints(and
                    (after (and
                                (ON D B) 
                                (ON B P) 
                                (ON P F) 
                                (ON F G) 
                                (ON G K) 
                                (ON K I) 
                                (ON I L)
                                (ON L J) 
                                (ON J H) 
                                (ON H A) 
                                (ON A N) 
                                (ON N E) 
                                (ON E M) 
                                (ON M C)
                                (ON C O)
                            ) t1)
                )    
))
