(define (problem BLOCKS-15-1)
(:domain BLOCKS)
     (:requirements :strips :typing :negative-preconditions :htn :equality)

(:objects F I G O J H N E D B L A C K M  - block)
(:INIT 
	(CLEAR G) 
    (CLEAR O) 
    (ONTABLE I) 
    (ONTABLE M) 
    (ON G L) 
    (ON L F) 
    (ON F C)
    (ON C N) 
    (ON N E) 
    (ON E H) 
    (ON H D) 
    (ON D A) 
    (ON A K) 
    (ON K B) 
    (ON B J)
    (ON J I) 
    (ON O M)
    (HANDEMPTY))
(:goal
     :tasks  (
            (tag t1 (do_put_on L H))
            (tag t2 (do_put_on I L))
            (tag t3 (do_put_on O I))
            (tag t4 (do_put_on N O))
            (tag t5 (do_put_on C N))
            (tag t6 (do_put_on B C))
            (tag t7 (do_put_on A B))
            (tag t8 (do_put_on M A))
            (tag t9 (do_put_on E M))
            (tag t10 (do_put_on J E))
            (tag t11 (do_put_on K J))
            (tag t12 (do_put_on F K))
            (tag t13 (do_put_on G F))
            (tag t14 (do_put_on D G))

        )

    :constraints(and
                    (after (and
                                (ON D G) 
                                (ON G F) 
                                (ON F K) 
                                (ON K J) 
                                (ON J E) 
                                (ON E M) 
                                (ON M A)
                                (ON A B) 
                                (ON B C) 
                                (ON C N) 
                                (ON N O) 
                                (ON O I) 
                                (ON I L) 
                                (ON L H)
                            ) t1)
                )    
))
