(define (problem BLOCKS-14-0)
(:domain BLOCKS)
     (:requirements :strips :typing :negative-preconditions :htn :equality)

(:objects F I G J H N E D B L A C K M  - block)
(:INIT 
	(CLEAR A) 
    (CLEAR G) 
    (CLEAR F) 
    (ONTABLE E) 
    (ONTABLE N) 
    (ONTABLE F)
    (ON A J) 
    (ON J H) 
    (ON H M) 
    (ON M K) 
    (ON K C) 
    (ON C L) 
    (ON L B) 
    (ON B E)
    (ON G D) 
    (ON D I) 
    (ON I N)
    (HANDEMPTY))
(:goal
     :tasks  (
            (tag t1 (do_put_on A H))
            (tag t2 (do_put_on M A))
            (tag t3 (do_put_on D M))
            (tag t4 (do_put_on G D))
            (tag t5 (do_put_on K G))
            (tag t6 (do_put_on C K))
            (tag t7 (do_put_on N C))
            (tag t8 (do_put_on I N))
            (tag t9 (do_put_on J I))
            (tag t10 (do_put_on B J))
            (tag t11 (do_put_on F B))
            (tag t12 (do_put_on L F))
            (tag t13 (do_put_on E L))

        )

    :constraints(and
                    (after (and
                                (ON E L) 
                                (ON L F) 
                                (ON F B) 
                                (ON B J) 
                                (ON J I) 
                                (ON I N) 
                                (ON N C)
                                (ON C K) 
                                (ON K G) 
                                (ON G D) 
                                (ON D M) 
                                (ON M A) 
                                (ON A H)
                            ) t1)
                )    
))
