(define (problem BLOCKS-11-2)
(:domain BLOCKS)
     (:requirements :strips :typing :negative-preconditions :htn :equality)

(:objects F I J H E D B A C K G - block)
(:INIT 
	(CLEAR B) 
    (CLEAR I) 
    (ONTABLE A) 
    (ONTABLE G) 
    (ON B H) 
    (ON H K) 
    (ON K F)
    (ON F C) 
    (ON C D) 
    (ON D J) 
    (ON J A) 
    (ON I E) 
    (ON E G)
    (HANDEMPTY))
(:goal
     :tasks  (
            (tag t1 (do_put_on F K))
            (tag t2 (do_put_on A F))
            (tag t3 (do_put_on H A))
            (tag t4 (do_put_on B H))
            (tag t5 (do_put_on J B))
            (tag t6 (do_put_on E J))
            (tag t7 (do_put_on D E))
            (tag t8 (do_put_on C D))
            (tag t9 (do_put_on G C))
            (tag t10 (do_put_on I G))

        )

    :constraints(and
                    (after (and
                                (ON I G) 
                                (ON G C) 
                                (ON C D) 
                                (ON D E) 
                                (ON E J) 
                                (ON J B) 
                                (ON B H)
                                (ON H A) 
                                (ON A F) 
                                (ON F K)
                            ) t1)
                )    
))
