0 :  (pick ball6 rooma left  )  
1 :  (pick ball5 rooma right  )  
2 :  (move rooma roomb  )  
3 :  (drop ball6 roomb left  )  
4 :  (drop ball5 roomb right  )  
5 :  (move roomb rooma  )  
6 :  (pick ball4 rooma left  )  
7 :  (pick ball3 rooma right  )  
8 :  (move rooma roomb  )  
9 :  (drop ball4 roomb left  )  
10 :  (drop ball3 roomb right  )  
11 :  (move roomb rooma  )  
12 :  (pick ball2 rooma left  )  
13 :  (pick ball1 rooma right  )  
14 :  (move rooma roomb  )  
15 :  (drop ball2 roomb left  )  
16 :  (drop ball1 roomb right  )  
