0 :  (pick ball22 rooma left  )  
1 :  (pick ball21 rooma right  )  
2 :  (move rooma roomb  )  
3 :  (drop ball22 roomb left  )  
4 :  (drop ball21 roomb right  )  
5 :  (move roomb rooma  )  
6 :  (pick ball20 rooma left  )  
7 :  (pick ball19 rooma right  )  
8 :  (move rooma roomb  )  
9 :  (drop ball20 roomb left  )  
10 :  (drop ball19 roomb right  )  
11 :  (move roomb rooma  )  
12 :  (pick ball18 rooma left  )  
13 :  (pick ball17 rooma right  )  
14 :  (move rooma roomb  )  
15 :  (drop ball18 roomb left  )  
16 :  (drop ball17 roomb right  )  
17 :  (move roomb rooma  )  
18 :  (pick ball16 rooma left  )  
19 :  (pick ball15 rooma right  )  
20 :  (move rooma roomb  )  
21 :  (drop ball16 roomb left  )  
22 :  (drop ball15 roomb right  )  
23 :  (move roomb rooma  )  
24 :  (pick ball14 rooma left  )  
25 :  (pick ball13 rooma right  )  
26 :  (move rooma roomb  )  
27 :  (drop ball14 roomb left  )  
28 :  (drop ball13 roomb right  )  
29 :  (move roomb rooma  )  
30 :  (pick ball12 rooma left  )  
31 :  (pick ball11 rooma right  )  
32 :  (move rooma roomb  )  
33 :  (drop ball12 roomb left  )  
34 :  (drop ball11 roomb right  )  
35 :  (move roomb rooma  )  
36 :  (pick ball10 rooma left  )  
37 :  (pick ball9 rooma right  )  
38 :  (move rooma roomb  )  
39 :  (drop ball10 roomb left  )  
40 :  (drop ball9 roomb right  )  
41 :  (move roomb rooma  )  
42 :  (pick ball8 rooma left  )  
43 :  (pick ball7 rooma right  )  
44 :  (move rooma roomb  )  
45 :  (drop ball8 roomb left  )  
46 :  (drop ball7 roomb right  )  
47 :  (move roomb rooma  )  
48 :  (pick ball6 rooma left  )  
49 :  (pick ball5 rooma right  )  
50 :  (move rooma roomb  )  
51 :  (drop ball6 roomb left  )  
52 :  (drop ball5 roomb right  )  
53 :  (move roomb rooma  )  
54 :  (pick ball4 rooma left  )  
55 :  (pick ball3 rooma right  )  
56 :  (move rooma roomb  )  
57 :  (drop ball4 roomb left  )  
58 :  (drop ball3 roomb right  )  
59 :  (move roomb rooma  )  
60 :  (pick ball2 rooma left  )  
61 :  (pick ball1 rooma right  )  
62 :  (move rooma roomb  )  
63 :  (drop ball2 roomb left  )  
64 :  (drop ball1 roomb right  )  
